/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GameManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "cancelLobby"
      | "createLobby"
      | "getLobby"
      | "getLobbyCount"
      | "getLobbyPlayerCount"
      | "isPlayerInLobby"
      | "joinLobby"
      | "lobbies"
      | "lobbyCount"
      | "resolveGame"
      | "stakingAdapter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameResolved"
      | "LobbyCancelled"
      | "LobbyCreated"
      | "PlayerJoined"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelLobby",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLobby",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLobby",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLobbyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLobbyPlayerCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlayerInLobby",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinLobby",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lobbies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lobbyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveGame",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingAdapter",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelLobby",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLobby",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLobby", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLobbyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLobbyPlayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPlayerInLobby",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinLobby", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lobbies", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lobbyCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingAdapter",
    data: BytesLike
  ): Result;
}

export namespace GameResolvedEvent {
  export type InputTuple = [
    lobbyId: BigNumberish,
    winner: AddressLike,
    prizeAmount: BigNumberish
  ];
  export type OutputTuple = [
    lobbyId: bigint,
    winner: string,
    prizeAmount: bigint
  ];
  export interface OutputObject {
    lobbyId: bigint;
    winner: string;
    prizeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LobbyCancelledEvent {
  export type InputTuple = [lobbyId: BigNumberish];
  export type OutputTuple = [lobbyId: bigint];
  export interface OutputObject {
    lobbyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LobbyCreatedEvent {
  export type InputTuple = [
    lobbyId: BigNumberish,
    host: AddressLike,
    buyIn: BigNumberish,
    maxPlayers: BigNumberish
  ];
  export type OutputTuple = [
    lobbyId: bigint,
    host: string,
    buyIn: bigint,
    maxPlayers: bigint
  ];
  export interface OutputObject {
    lobbyId: bigint;
    host: string;
    buyIn: bigint;
    maxPlayers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [lobbyId: BigNumberish, player: AddressLike];
  export type OutputTuple = [lobbyId: bigint, player: string];
  export interface OutputObject {
    lobbyId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameManager extends BaseContract {
  connect(runner?: ContractRunner | null): GameManager;
  waitForDeployment(): Promise<this>;

  interface: GameManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  cancelLobby: TypedContractMethod<
    [lobbyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createLobby: TypedContractMethod<
    [buyIn: BigNumberish, maxPlayers: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getLobby: TypedContractMethod<
    [lobbyId: BigNumberish],
    [
      [string, bigint, bigint, string[], boolean, boolean, bigint] & {
        host: string;
        buyIn: bigint;
        maxPlayers: bigint;
        players: string[];
        resolved: boolean;
        active: boolean;
        prizePool: bigint;
      }
    ],
    "view"
  >;

  getLobbyCount: TypedContractMethod<[], [bigint], "view">;

  getLobbyPlayerCount: TypedContractMethod<
    [lobbyId: BigNumberish],
    [bigint],
    "view"
  >;

  isPlayerInLobby: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  joinLobby: TypedContractMethod<[lobbyId: BigNumberish], [void], "nonpayable">;

  lobbies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean, bigint] & {
        host: string;
        buyIn: bigint;
        maxPlayers: bigint;
        resolved: boolean;
        active: boolean;
        prizePool: bigint;
      }
    ],
    "view"
  >;

  lobbyCount: TypedContractMethod<[], [bigint], "view">;

  resolveGame: TypedContractMethod<
    [lobbyId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingAdapter: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelLobby"
  ): TypedContractMethod<[lobbyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLobby"
  ): TypedContractMethod<
    [buyIn: BigNumberish, maxPlayers: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLobby"
  ): TypedContractMethod<
    [lobbyId: BigNumberish],
    [
      [string, bigint, bigint, string[], boolean, boolean, bigint] & {
        host: string;
        buyIn: bigint;
        maxPlayers: bigint;
        players: string[];
        resolved: boolean;
        active: boolean;
        prizePool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLobbyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLobbyPlayerCount"
  ): TypedContractMethod<[lobbyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPlayerInLobby"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinLobby"
  ): TypedContractMethod<[lobbyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lobbies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean, bigint] & {
        host: string;
        buyIn: bigint;
        maxPlayers: bigint;
        resolved: boolean;
        active: boolean;
        prizePool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lobbyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveGame"
  ): TypedContractMethod<
    [lobbyId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakingAdapter"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "GameResolved"
  ): TypedContractEvent<
    GameResolvedEvent.InputTuple,
    GameResolvedEvent.OutputTuple,
    GameResolvedEvent.OutputObject
  >;
  getEvent(
    key: "LobbyCancelled"
  ): TypedContractEvent<
    LobbyCancelledEvent.InputTuple,
    LobbyCancelledEvent.OutputTuple,
    LobbyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "LobbyCreated"
  ): TypedContractEvent<
    LobbyCreatedEvent.InputTuple,
    LobbyCreatedEvent.OutputTuple,
    LobbyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;

  filters: {
    "GameResolved(uint256,address,uint256)": TypedContractEvent<
      GameResolvedEvent.InputTuple,
      GameResolvedEvent.OutputTuple,
      GameResolvedEvent.OutputObject
    >;
    GameResolved: TypedContractEvent<
      GameResolvedEvent.InputTuple,
      GameResolvedEvent.OutputTuple,
      GameResolvedEvent.OutputObject
    >;

    "LobbyCancelled(uint256)": TypedContractEvent<
      LobbyCancelledEvent.InputTuple,
      LobbyCancelledEvent.OutputTuple,
      LobbyCancelledEvent.OutputObject
    >;
    LobbyCancelled: TypedContractEvent<
      LobbyCancelledEvent.InputTuple,
      LobbyCancelledEvent.OutputTuple,
      LobbyCancelledEvent.OutputObject
    >;

    "LobbyCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      LobbyCreatedEvent.InputTuple,
      LobbyCreatedEvent.OutputTuple,
      LobbyCreatedEvent.OutputObject
    >;
    LobbyCreated: TypedContractEvent<
      LobbyCreatedEvent.InputTuple,
      LobbyCreatedEvent.OutputTuple,
      LobbyCreatedEvent.OutputObject
    >;

    "PlayerJoined(uint256,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
  };
}
