/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameManager } from "./GameManager";
export type { StakingAdapter } from "./StakingAdapter";
export * as factories from "./factories";
export { GameManager__factory } from "./factories/GameManager__factory";
export { StakingAdapter__factory } from "./factories/StakingAdapter__factory";
