/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LobbyFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allMatches"
      | "cancelMatch"
      | "createMatch"
      | "getMatchInfo"
      | "getMatches"
      | "getOpenMatches"
      | "isMatch"
      | "matchCount"
      | "owner"
      | "submitResults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchCreated" | "MatchStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allMatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatches",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitResults",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "allMatches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOpenMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResults",
    data: BytesLike
  ): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchAddr: AddressLike,
    creator: AddressLike,
    maxPlayers: BigNumberish,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    matchAddr: string,
    creator: string,
    maxPlayers: bigint,
    entryFee: bigint
  ];
  export interface OutputObject {
    matchAddr: string;
    creator: string;
    maxPlayers: bigint;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchStatusChangedEvent {
  export type InputTuple = [matchAddr: AddressLike, status: BigNumberish];
  export type OutputTuple = [matchAddr: string, status: bigint];
  export interface OutputObject {
    matchAddr: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LobbyFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LobbyFactory;
  waitForDeployment(): Promise<this>;

  interface: LobbyFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allMatches: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  cancelMatch: TypedContractMethod<
    [matchAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  createMatch: TypedContractMethod<
    [_maxPlayers: BigNumberish, _entryFee: BigNumberish],
    [string],
    "payable"
  >;

  getMatchInfo: TypedContractMethod<
    [matchAddr: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        _creator: string;
        _maxPlayers: bigint;
        _entryFee: bigint;
        _status: bigint;
        _playerCount: bigint;
        _prizePool: bigint;
      }
    ],
    "view"
  >;

  getMatches: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getOpenMatches: TypedContractMethod<[], [string[]], "view">;

  isMatch: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  matchCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  submitResults: TypedContractMethod<
    [matchAddr: AddressLike, _players: AddressLike[], _scores: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allMatches"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "cancelMatch"
  ): TypedContractMethod<[matchAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [_maxPlayers: BigNumberish, _entryFee: BigNumberish],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getMatchInfo"
  ): TypedContractMethod<
    [matchAddr: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        _creator: string;
        _maxPlayers: bigint;
        _entryFee: bigint;
        _status: bigint;
        _playerCount: bigint;
        _prizePool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatches"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOpenMatches"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isMatch"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitResults"
  ): TypedContractMethod<
    [matchAddr: AddressLike, _players: AddressLike[], _scores: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchStatusChanged"
  ): TypedContractEvent<
    MatchStatusChangedEvent.InputTuple,
    MatchStatusChangedEvent.OutputTuple,
    MatchStatusChangedEvent.OutputObject
  >;

  filters: {
    "MatchCreated(address,address,uint8,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchStatusChanged(address,uint8)": TypedContractEvent<
      MatchStatusChangedEvent.InputTuple,
      MatchStatusChangedEvent.OutputTuple,
      MatchStatusChangedEvent.OutputObject
    >;
    MatchStatusChanged: TypedContractEvent<
      MatchStatusChangedEvent.InputTuple,
      MatchStatusChangedEvent.OutputTuple,
      MatchStatusChangedEvent.OutputObject
    >;
  };
}
