/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StakingAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APY_BPS"
      | "FAUCET_COOLDOWN"
      | "FAUCET_MAX"
      | "FAUCET_MIN"
      | "creditRewards"
      | "deductRewards"
      | "deposit"
      | "faucet"
      | "faucetCooldownRemaining"
      | "gameManager"
      | "getAccruedRewards"
      | "getAvailableRewards"
      | "getPrincipal"
      | "lastFaucetClaim"
      | "owner"
      | "principal"
      | "rewardBalance"
      | "setGameManager"
      | "stakeTimestamp"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "FaucetClaimed"
      | "GameManagerSet"
      | "RewardsCredited"
      | "RewardsDeducted"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "APY_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FAUCET_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FAUCET_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FAUCET_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deductRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "faucet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "faucetCooldownRemaining",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gameManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccruedRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrincipal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastFaucetClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "principal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "APY_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FAUCET_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FAUCET_MAX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FAUCET_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deductRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "faucet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "faucetCooldownRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccruedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFaucetClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "principal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameManagerSetEvent {
  export type InputTuple = [gameManager: AddressLike];
  export type OutputTuple = [gameManager: string];
  export interface OutputObject {
    gameManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsCreditedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDeductedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    principal: BigNumberish,
    rewards: BigNumberish
  ];
  export type OutputTuple = [user: string, principal: bigint, rewards: bigint];
  export interface OutputObject {
    user: string;
    principal: bigint;
    rewards: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): StakingAdapter;
  waitForDeployment(): Promise<this>;

  interface: StakingAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APY_BPS: TypedContractMethod<[], [bigint], "view">;

  FAUCET_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  FAUCET_MAX: TypedContractMethod<[], [bigint], "view">;

  FAUCET_MIN: TypedContractMethod<[], [bigint], "view">;

  creditRewards: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deductRewards: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  faucet: TypedContractMethod<[], [void], "nonpayable">;

  faucetCooldownRemaining: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  gameManager: TypedContractMethod<[], [string], "view">;

  getAccruedRewards: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getAvailableRewards: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getPrincipal: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  lastFaucetClaim: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  principal: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  rewardBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setGameManager: TypedContractMethod<
    [_gameManager: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeTimestamp: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FAUCET_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FAUCET_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FAUCET_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creditRewards"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deductRewards"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "faucet"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "faucetCooldownRemaining"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gameManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAccruedRewards"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableRewards"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrincipal"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastFaucetClaim"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "principal"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGameManager"
  ): TypedContractMethod<[_gameManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "FaucetClaimed"
  ): TypedContractEvent<
    FaucetClaimedEvent.InputTuple,
    FaucetClaimedEvent.OutputTuple,
    FaucetClaimedEvent.OutputObject
  >;
  getEvent(
    key: "GameManagerSet"
  ): TypedContractEvent<
    GameManagerSetEvent.InputTuple,
    GameManagerSetEvent.OutputTuple,
    GameManagerSetEvent.OutputObject
  >;
  getEvent(
    key: "RewardsCredited"
  ): TypedContractEvent<
    RewardsCreditedEvent.InputTuple,
    RewardsCreditedEvent.OutputTuple,
    RewardsCreditedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDeducted"
  ): TypedContractEvent<
    RewardsDeductedEvent.InputTuple,
    RewardsDeductedEvent.OutputTuple,
    RewardsDeductedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "FaucetClaimed(address,uint256)": TypedContractEvent<
      FaucetClaimedEvent.InputTuple,
      FaucetClaimedEvent.OutputTuple,
      FaucetClaimedEvent.OutputObject
    >;
    FaucetClaimed: TypedContractEvent<
      FaucetClaimedEvent.InputTuple,
      FaucetClaimedEvent.OutputTuple,
      FaucetClaimedEvent.OutputObject
    >;

    "GameManagerSet(address)": TypedContractEvent<
      GameManagerSetEvent.InputTuple,
      GameManagerSetEvent.OutputTuple,
      GameManagerSetEvent.OutputObject
    >;
    GameManagerSet: TypedContractEvent<
      GameManagerSetEvent.InputTuple,
      GameManagerSetEvent.OutputTuple,
      GameManagerSetEvent.OutputObject
    >;

    "RewardsCredited(address,uint256)": TypedContractEvent<
      RewardsCreditedEvent.InputTuple,
      RewardsCreditedEvent.OutputTuple,
      RewardsCreditedEvent.OutputObject
    >;
    RewardsCredited: TypedContractEvent<
      RewardsCreditedEvent.InputTuple,
      RewardsCreditedEvent.OutputTuple,
      RewardsCreditedEvent.OutputObject
    >;

    "RewardsDeducted(address,uint256)": TypedContractEvent<
      RewardsDeductedEvent.InputTuple,
      RewardsDeductedEvent.OutputTuple,
      RewardsDeductedEvent.OutputObject
    >;
    RewardsDeducted: TypedContractEvent<
      RewardsDeductedEvent.InputTuple,
      RewardsDeductedEvent.OutputTuple,
      RewardsDeductedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
